language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --prefer-source

script: ./vendor/bin/phpunit

sudo: false